### ISSUE TITLE
metrics configuration

### ISSUE THREAD

**Issue by eonpatapon** [skydive-project/skydive-grafana-datasource#5]
When clicking on the metrics configuration, field is always set to Bytes even if it was configured to something else

**Comment by safchain** [comment]
@eonpatapon should be fixed by f5184eaebaa236b5a03b1cf135fa19b89de199d2

**Comment by eonpatapon** [comment]
I don't know why but now my build is failing with:

```
+ ./node_modules/grunt-cli/bin/grunt
Running "clean:0" (clean) task
>> 1 path cleaned.

Running "copy:src_to_dist" (copy) task
Created 3 directories, copied 5 files

Running "copy:img_to_dist" (copy) task
Copied 1 file

Running "copy:readme" (copy) task
Copied 1 file

Running "babel:dist" (babel) task

Running "babel:distTestNoSystemJs" (babel) task

Running "babel:distTestsSpecsNoSystemJs" (babel) task

Running "mochaTest:test" (mochaTest) task
>> Mocha exploded!
>> SyntaxError: Unexpected token {
>>     at exports.runInThisContext (vm.js:53:16)
>>     at Module._compile (module.js:374:25)
>>     at Object.Module._extensions..js (module.js:417:10)
>>     at Module.load (module.js:344:32)
>>     at Function.Module._load (module.js:301:12)
>>     at Module.require (module.js:354:17)
>>     at require (internal/module.js:12:17)
>>     at Object.<anonymous> (/opt/skydive-grafana-datasource/dist/test/spec/test-main.js:7:14)
>>     at Module._compile (module.js:410:26)
>>     at Object.Module._extensions..js (module.js:417:10)
Warning: Task "mochaTest:test" failed. Use --force to continue.
```
Doesn't seem to have a relation with your patch though...

**Comment by safchain** [comment]
Travis build is OK so probably a npm/grunt funny thing. the dist folder is up-to-date so you can use it without building.

**Comment by eonpatapon** [comment]
Ok, good to know, thx
